version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: canva-clone-postgres
    restart: always
    environment:
      POSTGRES_USER: canva-clone_owner
      POSTGRES_PASSWORD: uHgYZCs75vBL
      POSTGRES_DB: canva-clone
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
